

// useGLTF.preload('/model//sci_-_fi_computer_game_ready_2/scene.gltf')
// export default Computer

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sci-fi-computer-game-ready-53e7eeb0f69540d2892ad6aa5f47bd39
Title: Sci - fi computer game ready
*/
import { useGLTF } from '@react-three/drei'

const Computer = (props) => {
  const { nodes, materials } = useGLTF('/model//sci_-_fi_computer_game_ready_2/scene.gltf')
  return (
    <group {...props} dispose={null} >
      <group scale={0.01}>
        <group position={[0, 28.86872864, 312.19281006]} rotation={[-1.46876669, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_digital_displays_0.geometry}
            material={materials.digital_displays}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_digital_display_sides_0.geometry}
            material={materials.digital_display_sides}
          />
        </group>
        <group
          position={[0, 381.81222534, -82.65690613]}
          rotation={[-0.22890326, 0, 0]}
          scale={[100, 99.99999237, 99.99999237]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_digital_displays_0.geometry}
            material={materials.digital_displays}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_digital_display_sides_0.geometry}
            material={materials.digital_display_sides}
          />
        </group>
        <group
          position={[-0.00000104, 0, -94.76156616]}
          rotation={[0, Math.PI / 2, 0]}
          scale={123.80059814}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_metal_2_0.geometry}
            material={materials.metal_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_metal_1_0.geometry}
            material={materials.metal_1}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model//sci_-_fi_computer_game_ready_2/scene.gltf')
export default Computer